### ISSUE TITLE
0.7.4 performance

### ISSUE THREAD

**Issue by bmateusz** [bkiers/Liqp#92] opened 2018-06-29 14:14 UTC
The latest release seems slower, I benchmarked with our project:
0.7.2: 20.49 secs
0.7.3: 21.162 secs
0.7.4: 48.954 secs

Anyone else experienced this? We don't use any advanced features.

**Comment by bkiers** [comment] 2018-06-29 18:55
Hmmm, some things are faster, like custom tags: https://github.com/bkiers/Liqp/issues/37

Could you include your benchmark(s) code?

**Comment by bmateusz** [comment] 2018-06-30 12:01
I can't since it's not open source. I will try to make a small example.

**Comment by mbaumbach** [comment] 2018-07-06 16:37
I'm also experiencing this and seems to be much more pronounced with larger templates. I found a mention in the ANTL4 readme about using a [two-stage parsing process to fix performance issues](https://github.com/antlr/antlr4/blob/master/doc/faq/general.md#why-is-my-expression-parser-slow).

I've submitted a PR #93 which implements a similar suggestion and I saw templates that were taking 100ms to parse drop down to 5ms.

**Comment by mbaumbach** [comment] 2018-07-06 17:18
I don't think this entirely resolves the issue though. I created a simple "benchmark" here: https://gist.github.com/mbaumbach/e6e5114bb9220fdd37088608dab9e463

And here's the timings for the various versions:

```
0.7.3

Parsing small
Parse time (attempt: 1): 583
Parse time (attempt: 2): 0
Parse time (attempt: 3): 0
Parse time (attempt: 4): 0
Parse time (attempt: 5): 0
Parse time (attempt: 6): 0
Parse time (attempt: 7): 0
Parse time (attempt: 8): 0
Parse time (attempt: 9): 0
Parse time (attempt: 10): 0
Parsing medium
Parse time (attempt: 1): 25
Parse time (attempt: 2): 8
Parse time (attempt: 3): 7
Parse time (attempt: 4): 4
Parse time (attempt: 5): 6
Parse time (attempt: 6): 10
Parse time (attempt: 7): 5
Parse time (attempt: 8): 5
Parse time (attempt: 9): 4
Parse time (attempt: 10): 2
Parsing large
Parse time (attempt: 1): 16
Parse time (attempt: 2): 17
Parse time (attempt: 3): 13
Parse time (attempt: 4): 12
Parse time (attempt: 5): 10
Parse time (attempt: 6): 10
Parse time (attempt: 7): 13
Parse time (attempt: 8): 20
Parse time (attempt: 9): 13
Parse time (attempt: 10): 10

0.7.4

Parsing small
Parse time (attempt: 1): 688
Parse time (attempt: 2): 15
Parse time (attempt: 3): 10
Parse time (attempt: 4): 11
Parse time (attempt: 5): 15
Parse time (attempt: 6): 10
Parse time (attempt: 7): 8
Parse time (attempt: 8): 8
Parse time (attempt: 9): 8
Parse time (attempt: 10): 8
Parsing medium
Parse time (attempt: 1): 812
Parse time (attempt: 2): 590
Parse time (attempt: 3): 447
Parse time (attempt: 4): 302
Parse time (attempt: 5): 224
Parse time (attempt: 6): 197
Parse time (attempt: 7): 167
Parse time (attempt: 8): 168
Parse time (attempt: 9): 227
Parse time (attempt: 10): 171
Parsing large
Parse time (attempt: 1): 957
Parse time (attempt: 2): 879
Parse time (attempt: 3): 852
Parse time (attempt: 4): 838
Parse time (attempt: 5): 836
Parse time (attempt: 6): 835
Parse time (attempt: 7): 933
Parse time (attempt: 8): 845
Parse time (attempt: 9): 843
Parse time (attempt: 10): 894

0.7.4 + PR

Parsing small
Parse time (attempt: 1): 758
Parse time (attempt: 2): 3
Parse time (attempt: 3): 4
Parse time (attempt: 4): 2
Parse time (attempt: 5): 2
Parse time (attempt: 6): 2
Parse time (attempt: 7): 1
Parse time (attempt: 8): 2
Parse time (attempt: 9): 1
Parse time (attempt: 10): 1
Parsing medium
Parse time (attempt: 1): 84
Parse time (attempt: 2): 73
Parse time (attempt: 3): 77
Parse time (attempt: 4): 72
Parse time (attempt: 5): 73
Parse time (attempt: 6): 71
Parse time (attempt: 7): 68
Parse time (attempt: 8): 72
Parse time (attempt: 9): 67
Parse time (attempt: 10): 55
Parsing large
Parse time (attempt: 1): 224
Parse time (attempt: 2): 251
Parse time (attempt: 3): 104
Parse time (attempt: 4): 103
Parse time (attempt: 5): 102
Parse time (attempt: 6): 179
Parse time (attempt: 7): 117
Parse time (attempt: 8): 86
Parse time (attempt: 9): 86
Parse time (attempt: 10): 94
```

So it's a pretty big improvement, but still pretty far off from 0.7.3 performance.

**Comment by bkiers** [comment] 2018-07-10 07:39
Again, thanks @mbaumbach. When I find the time, I'll see if I can do some testing/profiling to see if I can pin-point some hotspots. Your PR has been merged but we'll leave this issue open for now.

**Comment by bmateusz** [comment] 2018-07-10 09:12
Thanks @mbaumbach, looks much better! 👍 
Although it seems to me that the performance problem is with antlr4

**Comment by mbaumbach** [comment] 2018-07-28 16:56
@bkiers @bmateusz I think we're getting a little closer to finding the culprit. I think the problem is with the LiquidLexer.g4 definition. I found that if I removed the stripSpacesAroundTags and stripSingleLine portions of the out and tag start/end definitions, it greatly improved the speed. The modified code is: https://gist.github.com/mbaumbach/454c179dcd08f1837edebb3987a34a30. Obviously this doesn't pass the tests, but still works for most liquid templates.

Here's the new results:

```
Parsing small
Parse time (attempt: 1): 887
Parse time (attempt: 2): 1
Parse time (attempt: 3): 1
Parse time (attempt: 4): 1
Parse time (attempt: 5): 1
Parse time (attempt: 6): 1
Parse time (attempt: 7): 0
Parse time (attempt: 8): 1
Parse time (attempt: 9): 1
Parse time (attempt: 10): 0
Parsing medium
Parse time (attempt: 1): 22
Parse time (attempt: 2): 11
Parse time (attempt: 3): 13
Parse time (attempt: 4): 14
Parse time (attempt: 5): 13
Parse time (attempt: 6): 18
Parse time (attempt: 7): 11
Parse time (attempt: 8): 9
Parse time (attempt: 9): 11
Parse time (attempt: 10): 22
Parsing large
Parse time (attempt: 1): 36
Parse time (attempt: 2): 29
Parse time (attempt: 3): 23
Parse time (attempt: 4): 21
Parse time (attempt: 5): 24
Parse time (attempt: 6): 20
Parse time (attempt: 7): 22
Parse time (attempt: 8): 26
Parse time (attempt: 9): 15
Parse time (attempt: 10): 15
```

I came across looking at the whitespace and lexer as the potential issue by reading up on this thread a bit: https://groups.google.com/forum/#!searchin/antlr-discussion/performance%7Csort:date/antlr-discussion/lmzstX6_nS0/mQZMhdCiBwAJ

I'm still a noob when it comes to ANTLR, but I think the parsing being slow is because the lexer is generating too many tokens, so I suspect improved handling of whitespace might improve the performance.

**Comment by bkiers** [comment] 2018-08-02 13:38
Nice work @mbaumbach! I've just got back from holiday, so I've got some other work lined up for now, but I will get back on this. Thanks.

**Comment by mbaumbach** [comment] 2018-09-20 14:05
With the work from @JD557 in #103, this is almost back to the performance numbers we saw in 0.7.3 and you may be able to chalk up the difference to ANTLR3 and 4 differences. I'm interested in what @bmateusz sees, as the performance is greatly improved in my apps now.

**Comment by bkiers** [comment] 2018-12-03 21:18
Any objections in closing this issue, or is someone still working on something?

Again, thank you all for your great help!

**Comment by mbaumbach** [comment] 2018-12-03 21:19
@bkiers I'd agree with it being closed. Performance is pretty close to what it was at!

**Closed** 2018-12-03 22:47 UTC
