### ISSUE TITLE
Integer and Float Comparisons After Using Times Filter

### ISSUE THREAD

**Issue by shalaniw** [bkiers/Liqp#267] opened 2023-03-15 22:17 UTC
I'm observing some odd behavior when using the times filter with a float value. In both of the cases below, the `comparingValue` variable should be `98.0`. In both tests I check if `99` is `greater than` that value. For some reason, the case with the `times` filter fails with `false` and the case with the `divide_by` filter passes with `true`. 

```
    // Test Fails
    @Test
    public void testUseVariableAndTimesFilter() throws RecognitionException {
        assertPatternResultEquals(TemplateParser.DEFAULT, "true", 
            "{% assign comparingValue = 98 | times: 1.0 %}{{ 99 > comparingValue }}");
    }

    // Test Passes   
    @Test
    public void testUseVariableAndDividedByFilter() throws RecognitionException {
        assertPatternResultEquals(TemplateParser.DEFAULT, "true",
            "{% assign comparingValue = 98 | divided_by: 1.0 %}{{ 99 > comparingValue }}");
    }
```

I believe this is a bug and that both cases should pass with `true`.

**Comment by msangel** [comment] 2023-03-16 18:55
Hello!
Thanks for the report. Bug confirmed.
I already have a fix for this, but the problem seems to be wider, so more investigation needed.

tech details: problem was in this part of code:
```
        return (a instanceof Number) && (b instanceof Number) &&
                super.asNumber(a).doubleValue() > super.asNumber(b).doubleValue();
```
in a case when variables are string (and in this case they are since variable evaluation perform to string)

**Comment by msangel** [comment] 2023-03-16 20:03
Another interesting question is about compatibility of this samples with original liquid.
In Jekyll I got `"98"` and in Liquid I got 
```bash
/usr/lib/ruby/gems/3.1.0/gems/liquid-5.4.0/lib/liquid/parser.rb:18:in `consume': Liquid syntax error: Expected end_of_string but found comparison in "{{ '98' > comparingValue }}" (Liquid::SyntaxError)
```

So in solving this issue the preference for ruby's implementation will be given.

**Comment by kohlschuetter** [comment] 2023-03-16 20:34
@msangel Shouldn't we follow Jekyll's implementation here? We might control this using Flavor.

**Comment by msangel** [comment] 2023-03-16 20:43
Yep, we should.

**Comment by msangel** [comment] 2023-03-16 22:04
Have to debug ruby.... Looks like Liquid version of `variable` is not designed for printing anything but atom. it consume the atom and expects the end, even if there mote tokens (that's where the error came from)
![image](https://user-images.githubusercontent.com/773163/225762835-3483b49b-71e1-4c83-b74e-b36b8c99e1fe.png)

**Comment by msangel** [comment] 2023-03-16 22:06
Will debug Jekyll ones later....

**Comment by msangel** [comment] 2023-03-16 22:10
More of Liquid (just for self-documenting first)
![image](https://user-images.githubusercontent.com/773163/225763793-76acade8-991f-4c80-9b47-3761f875cb4c.png)

**Comment by msangel** [comment] 2023-03-16 22:16
Jekyll have similar behavior but it simply return first atom(without any further expectations)
![image](https://user-images.githubusercontent.com/773163/225764682-0bba7ee8-b52f-41b5-9297-924fdbde1733.png)

**Comment by msangel** [comment] 2023-03-17 01:01
Jekyll default configuration is `:warn`:
![image](https://user-images.githubusercontent.com/773163/225785616-f7b06fdb-4d8f-4e3b-baa5-9825c1326ce0.png)
Liquid default is `lax`:
![image](https://user-images.githubusercontent.com/773163/225785719-5f76fd22-77e2-4ce1-b4b3-bb364b7b2a11.png)

**Comment by msangel** [comment] 2023-03-17 01:07
Currently, the library has only `strict` and  `non-strict`  modes. And this strictness is applied only to context behavior, as partial parsing is not supported. Template source is tokenized no mapper what or general fail.

**Comment by msangel** [comment] 2023-03-17 01:16
So we have two options: 

- Have ruby compatibility with their weirdness - `not execute expressions in out tag but simply print the first atom`
- Have proper and predictable behavior that meets any expectations but goes against the original templator - `execute expressions in out tag and print evaluated result`

What would you pick?
@bkiers

**Comment by bkiers** [comment] 2023-03-17 07:27
During my active development, I've always thrived for compatibility with Ruby's Liquid library. But given this is rather odd, I'd go for the predictable route. But given I am not actively working on this, if you'd rather be compatible with Ruby, I'd support that too @msangel.

**Comment by msangel** [comment] 2023-03-19 23:46
Ok. My decision is: by default this will behave as expected(as of now). BUT there will be a flag that will turn on either the first token either error on something more than one atom. If someone will need full compatibility, the one will get it. 
Technical notes: here on parser level, lexer is not affected:
```antlr
output
 : outStart expr filter* OutEnd
 ;
````

**Comment by msangel** [comment] 2023-08-02 02:05
Closed fully in https://github.com/bkiers/Liqp/commit/af65618808cf686770ec2ddd7bfbed55dabf537e accoarding to exact ruby behavior

**Closed by msangel** 2023-08-02 02:05 UTC
